version: '3.8'

services:
  backend:
    image: agape/backend:version
    build: ./Backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    image: agape/frontend:version
    build: ./frontend 
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network: